# Generated by Django 4.1 on 2022-10-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="floor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("floorName", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="lift",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("liftName", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="peoplecounting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rectime", models.DateTimeField()),
                ("liftNum", models.PositiveIntegerField()),
                ("floorNum", models.PositiveIntegerField()),
                ("numOfPeople", models.PositiveIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
