# Generated by Django 4.1 on 2022-10-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="floor", name="created",),
        migrations.RemoveField(model_name="floor", name="modified",),
        migrations.RemoveField(model_name="lift", name="created",),
        migrations.RemoveField(model_name="lift", name="modified",),
        migrations.RemoveField(model_name="peoplecounting", name="created",),
        migrations.RemoveField(model_name="peoplecounting", name="modified",),
    ]
