# Generated by Django 4.1 on 2022-10-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_remove_floor_created_remove_floor_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplecounting",
            name="floorNum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.floor"
            ),
        ),
        migrations.AlterField(
            model_name="peoplecounting",
            name="liftNum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.lift"
            ),
        ),
    ]
