# Generated by Django 4.1 on 2022-10-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_alter_peoplecounting_floornum_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="peoplecounting", old_name="floorNum", new_name="floorID",
        ),
        migrations.RenameField(
            model_name="peoplecounting", old_name="liftNum", new_name="liftID",
        ),
    ]
